### ISSUE TITLE
Freshly build rul;eset freeze at the splash screen

### ISSUE THREAD

**Issue by Kashouryo** [ppy/osu-templates#21]
The game will freeze when I load my custom ruleset(a fresh ruleset-scrolling-example).
It happens on both official release and local debug.
When I start the game, it will freeze on the splash screen, not even showing my supporter status.
![image](https://user-images.githubusercontent.com/37679684/65844446-58c21700-e304-11e9-8a34-699a726db211.png)

**Comment by peppy** [comment]
Are you using visualtests? It doesn't look like it.

**Comment by Kashouryo** [comment]
I dropped the dll into the game directory. Do I need to use visualtests instead?

**Comment by peppy** [comment]
The templates come with completely setup testing environments. Please use them. If, once you are done with implementing something, you have issues loading into a running game, open an issue against the [osu](https://github.com/ppy/osu) project. Make sure to provide stack traces and logs at very least when you do this.
