### ISSUE TITLE
Figure out a way to regularly bump version of `osu.Game`

### ISSUE THREAD

**Issue by bdach** [ppy/osu-templates#31]
Version specifications of `osu.Game` in the templates are [positively archaic](https://github.com/ppy/osu-templates/blob/870a90486494de9644075536683c9ce4aecf689d/templates/ruleset-empty/osu.Game.Rulesets.EmptyFreeform/osu.Game.Rulesets.EmptyFreeform.csproj#L13), which [leads to confusion](https://github.com/ppy/osu/issues/11451#issuecomment-757207322) of users of the template.

We should be looking at a way of regularly bumping said version (possibly via dependabot and manual deploys - but something more automated or templatey might be better, since doing that the "normal" way is bound to be tedious; this should ideally be low-maintenance). Maybe the way forward is re-integration back into the game repository, similarly to how the framework template project operates.

**Comment by peppy** [comment]
Closed via https://github.com/ppy/osu/pull/12295.
