### ISSUE TITLE
Add non-scrolling sample projects

### ISSUE THREAD

**Issue by peppy** [ppy/osu-templates#6]
Two further projects should be added for rulesets which do not derive `DrawableScrollingRuleset` / `DrawableScrollingPlayfield`, as these handle slightly differently.

**Comment by frenzibyte** [comment]
Are we adding a non-scrolling example as well? not sure if there are any non-scrolling rulesets to put

**Comment by smoogipoo** [comment]
Don't see why not, maybe something like stable's practice mod.

**Comment by frenzibyte** [comment]
> Don't see why not, maybe something like stable's practice mod.

Oh, didn't know about that. seems to be nice and easy to implement! 👍
